version: '3.2'

networks:
  ava:
    driver: bridge

services:
  redis:
    networks:
      ava:
    image: redis:alpine
    expose:
      - "6379"
    ports:
      - "6379:6379"

  php:
    networks:
      ava:
    build:
      context: .
      dockerfile: docker/dev/Dockerfile.php
    volumes:
      - type: bind
        source: ./src
        target: /app
    environment:
      - TERM=xterm-256color
    ports:
      - "25:25"

  nginx:
    networks:
      ava:
    build:
      context: .
      dockerfile: docker/dev/Dockerfile.nginx
    volumes:
      - type: bind
        source: ./src
        target: /app
      - type: bind
        source: ./site/dev/ca
        target: /etc/nginx/ssl
      - type: bind
        source: ./site/dev/default.conf
        target: /etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
      - "443:443"

  pgsql:
    networks:
      ava:
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=1234asdf
