FROM nginx:alpine

COPY site/production /etc/nginx/conf.d

RUN mkdir /etc/nginx/ssl
COPY site/ca /etc/nginx/ssl

RUN chmod 700 /etc/nginx/ssl
RUN chmod -R 600 /etc/nginx/ssl/bundle.crt /etc/nginx/ssl/server.key /etc/nginx/ssl/ovroot.cer /etc/nginx/ssl/ca.cer

WORKDIR /app