version: '3.2'

networks:
  ga:
    driver: bridge

services:
  redis:
    networks:
      ga:
    image: redis:alpine
    expose:
      - "6379"
    ports:
      - "6379:6379"

  php:
    networks:
      ga:
    build:
      context: .
      dockerfile: docker/production/Dockerfile.php
    volumes:
      - type: bind
        source: ./src
        target: /app
    environment:
      - TERM=xterm-256color
    ports:
      - "25:25"

  nginx:
    networks:
      ga:
    build:
      context: .
      dockerfile: docker/production/Dockerfile.nginx
    volumes:
      - type: bind
        source: ./src
        target: /app
      #- type: bind
      #  source: ./site/production/ca
      #  target: /etc/nginx/ssl
      - type: bind
        source: ./site/production/default.conf
        target: /etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
      - "443:443"

  pgsql:
    networks:
      ga:
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=trade168
